apiVersion: v1
kind: Service
metadata:
  name: oauth
spec:
  selector:
    app: oauth
    tier: backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: oauth
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: oauth
        tier: backend
        track: stable
    spec:
      containers:
        - name: oauth-python
          image: "oauth-python:v1"
          ports:
            - name: http
              containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
spec:
  selector:
    app: zipkin
    tier: backend
  ports:
  - protocol: TCP
    port: 9411
    targetPort: 9411
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: zipkin
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: zipkin
        tier: backend
        track: stable
    spec:
      containers:
        - name: zipkin
          image: "openzipkin/zipkin"
          ports:
            - name: http
              containerPort: 9411
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  selector:
    app: elasticsearch
    tier: backend
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 9200
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: elasticsearch
        tier: backend
        track: stable
    spec:
      containers:
        - name: elasticsearch
          image: "docker.elastic.co/elasticsearch/elasticsearch:6.2.2"
          ports:
            - name: http
              containerPort: 9200
