apiVersion: v1
kind: Service
metadata:
  name: colors
spec:
  selector:
    app: color
    tier: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: colors
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: color
        tier: frontend
        track: stable
    spec:
      containers:
        - name: colors-python
          image: "colors-python:v1"
          ports:
            - name: http
              containerPort: 5000